version: "3.7"

services:
    github-runner:
      image: thuong/github-runner:latest
      environment:
        RUNNER_NAME: "github-runner"
        RUNNER_ORGANIZATION_URL: ${RUNNER_ORGANIZATION_URL}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock